// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  var $main, content, converter;
  $main = $('#main');
  content = $('#README').html();
  converter = new Showdown.converter();
  $main.html(converter.makeHtml(content));
  return $('code').each(function(i, e) {
    var $e, html;
    $e = $(this);
    if ($e.hasClass('js') || $e.hasClass('coffeescript') || $e.hasClass('sh')) {
      if ($e.hasClass('js')) {
        $e.addClass('javascript');
      }
      if ($e.hasClass('sh')) {
        $e.addClass('bash');
      }
      html = $e.html().replace(/&amp;lt;/g, '<').replace(/&amp;gt;/g, '>').replace(/&amp;amp;/g, '&');
      $e.html(html);
      return hljs.highlightBlock(e);
    } else {
      return $e.addClass('no-highlight');
    }
  });
});
