// Generated by CoffeeScript 1.6.3
$(document).ready(function() {
  var $main, content, converter;
  $main = $('#main');
  content = $('#main').html();
  converter = new Showdown.converter();
  return $main.html(converter.makeHtml(content));
});

/*
//@ sourceMappingURL=readme.map
*/
